Repository devcordde/devmarkt-backend, pull requests merged in 2021-12, with the labels that each got.

#24 Add Danger Review
  .github/workflows/Danger.yml
  .gitignore
  dangerfile.js
  package-lock.json
  package.json
Labels: tooling

#31 Edit application banner
  backend/src/main/resources/micronaut-banner.txt
Labels: enhancement

#32 Add codeql action
  .github/workflows/codeql-analysis.yml
Labels: tooling

#34 Move Mongojack Micronaut integration to own module
  backend/build.gradle.kts
  backend/gradle.properties
  backend/src/main/java/club/devcord/devmarkt/Application.java
  backend/src/main/java/club/devcord/devmarkt/mongodb/service/template/TemplateDAO.java
  backend/src/main/resources/application.yml
  backend/src/test/resources/application-test.yml
  dto_common/build.gradle.kts
  gradle.properties
  micronaut-mongojack/build.gradle.kts
  micronaut-mongojack/src/main/java/club/devcord/devmarkt/micronaut_mongojack/Collection.java
  micronaut-mongojack/src/main/java/club/devcord/devmarkt/micronaut_mongojack/MongoCollectionFactory.java
  micronaut-mongojack/src/main/java/club/devcord/devmarkt/micronaut_mongojack/NoCollectionTypeProvided.java
  settings.gradle.kts
Labels: enhancement

#35 Add System.out and System.err linter
  dangerfile.js
Labels: tooling

#36 Resolve MongoCollection via generic (injection)
  backend/src/main/java/club/devcord/devmarkt/mongodb/service/template/TemplateDAO.java
  micronaut-mongojack/src/main/java/club/devcord/devmarkt/micronaut_mongojack/Collection.java
  micronaut-mongojack/src/main/java/club/devcord/devmarkt/micronaut_mongojack/MongoCollectionFactory.java
Labels: enhancement

#43 Update Micronaut to 3.2.3
  gradle.properties
Labels: dependencies
