Repository devcordde/devmarkt-backend, pull requests merged in 2022-03, with the labels that each got.

#69 Add Docker Image Deployment
  .github/workflows/ci.yml
Labels: tooling

#71 Update Danger to fix vulnerabilities
  package-lock.json
  package.json
Labels: dependencies, tooling

#77 Fix When.MAYBE warning
  backend/build.gradle.kts
Labels: bug

#76 64 input validation
  backend/build.gradle.kts
  backend/src/main/java/club/devcord/devmarkt/GraphQLFactory.java
  backend/src/main/java/club/devcord/devmarkt/entities/template/Question.java
  backend/src/main/java/club/devcord/devmarkt/entities/template/RawQuestion.java
  backend/src/main/java/club/devcord/devmarkt/entities/template/Template.java
  backend/src/main/java/club/devcord/devmarkt/graphql/GraphQLFactory.java
  backend/src/main/java/club/devcord/devmarkt/graphql/GraphQLType.java
  backend/src/main/java/club/devcord/devmarkt/responses/question/QuestionFailed.java
  backend/src/main/java/club/devcord/devmarkt/responses/template/TemplateFailed.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/graphql/common.graphql
  backend/src/main/resources/graphql/question.graphql
  backend/src/main/resources/graphql/validation.graphql
Labels: enhancement

#82 Test seeder
  backend/src/main/resources/db/seeder/R__Seed_Templates.sql
  backend/src/test/java/club/devcord/devmarkt/DevmarktTest.java
  backend/src/test/java/club/devcord/devmarkt/Helpers.java
  backend/src/test/java/club/devcord/devmarkt/Seed.java
  backend/src/test/java/club/devcord/devmarkt/graphql/Helpers.java
  backend/src/test/java/club/devcord/devmarkt/graphql/question/QuestionMutationTest.java
  backend/src/test/java/club/devcord/devmarkt/graphql/question/QuestionQueryTest.java
  backend/src/test/java/club/devcord/devmarkt/graphql/template/TemplateMutationTest.java
  backend/src/test/java/club/devcord/devmarkt/graphql/template/TemplateQueryTest.java
  backend/src/test/resources/application-test.yml
Labels: enhancement

#84 Add Danger check for Seeding related files
  dangerfile.js
Labels: tooling

#83 Add more tests
  backend/src/main/java/club/devcord/devmarkt/graphql/GraphQLFactory.java
  backend/src/main/java/club/devcord/devmarkt/graphql/question/QuestionMutation.java
  backend/src/main/java/club/devcord/devmarkt/graphql/template/TemplateMutation.java
  backend/src/main/java/club/devcord/devmarkt/graphql/template/TemplateQuery.java
  backend/src/main/java/club/devcord/devmarkt/responses/Fail.java
  backend/src/main/java/club/devcord/devmarkt/services/QuestionService.java
  backend/src/main/resources/db/seeder/R__Seed_Templates.sql
  backend/src/test/java/club/devcord/devmarkt/Helpers.java
  backend/src/test/java/club/devcord/devmarkt/Seed.java
  backend/src/test/java/club/devcord/devmarkt/graphql/question/QuestionMutationTest.java
  backend/src/test/java/club/devcord/devmarkt/graphql/template/TemplateMutationTest.java
  backend/src/test/java/club/devcord/devmarkt/logging/LoggingUtilTest.java
  backend/src/test/java/club/devcord/devmarkt/repositories/QuestionRepoTest.java
  backend/src/test/java/club/devcord/devmarkt/repositories/TemplateRepoTest.java
  backend/src/test/java/club/devcord/devmarkt/services/QuestionServiceTest.java
  backend/src/test/java/club/devcord/devmarkt/services/TemplateServiceTest.java
Labels: enhancement

#85 Implement QA System Tests
  .github/dependabot.yml
  .github/workflows/ci.yml
  backend/src/main/java/club/devcord/devmarkt/graphql/GraphQLFactory.java
  backend/src/main/java/club/devcord/devmarkt/graphql/SchemaResolver.java
  backend/src/main/resources/application-qa.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/graphql/schemas/common.graphql
  backend/src/main/resources/graphql/schemas/question.graphql
  backend/src/main/resources/graphql/schemas/template.graphql
  backend/src/main/resources/graphql/schemas/validation.graphql
  dangerfile.js
  qa/package.json
  qa/src/executor.js
  qa/src/fixtures/template/create-template-duplicated.json
  qa/src/fixtures/template/create-template-success.json
  qa/src/fixtures/template/template-names.json
  qa/src/fixtures/template/templates-only-questions.json
  qa/src/fixtures/template/templates.json
  qa/src/graphql/template/create-template.graphql
  qa/src/graphql/template/template-names.graphql
  qa/src/graphql/template/templates-only-questions.graphql
  qa/src/graphql/template/templates.graphql
  qa/src/spec/templates.spec.js
  qa/yarn.lock
Labels: tooling

#87 Enable qa for forks
  .github/workflows/ci.yml
Labels: tooling

#92 Update Logging configuration
  backend/build.gradle.kts
  backend/src/main/java/club/devcord/devmarkt/logging/AnsiColor.java
  backend/src/main/java/club/devcord/devmarkt/logging/ColorConverter.java
  backend/src/main/java/club/devcord/devmarkt/logging/ThrowableSpacer.java
  backend/src/main/resources/logback.xml
Labels: enhancement
