Repository devcordde/devmarkt-backend, pull requests merged in 2022-04, with the labels that each got.

#101 Add Danger check to prevent migration changes
  dangerfile.js
Labels: tooling

#104 Update readme
  README.md
Labels: documentation

#107 Fix ci tests in security-auth
  backend/src/test/resources/application-test.yml
Labels: fix

#105 QA Authentication Tests
  .gitignore
  .idea/runConfigurations/Application_QA_Template.xml
  .idea/runConfigurations/QA_Tests.xml
  backend/src/main/resources/application-qa.yml
  backend/src/main/resources/logback.xml
  qa/src/executor.js
  qa/src/fixtures/admin.key
  qa/src/fixtures/errors/unauthorized.json
  qa/src/fixtures/template/delete-template.json
  qa/src/fixtures/template/permission/create-permission-denied.json
  qa/src/fixtures/template/permission/delete-permission-denied.json
  qa/src/fixtures/template/permission/list-permission-denied.json
  qa/src/fixtures/test.key
  qa/src/graphql/template/create-template.graphql
  qa/src/graphql/template/delete-template.graphql
  qa/src/spec/template.spec.js
  qa/src/spec/templates.spec.js
  qa/src/spec_executor.js
Labels: qa
