Repository devcordde/devmarkt-backend, pull requests merged in 2022-05, with the labels that each got.

#115 Update readme
  README.md
Labels: documentation

#116 If "Foreign" auth is used, create user if not found
  backend/src/main/java/club/devcord/devmarkt/auth/UserProvider.java
  backend/src/main/java/club/devcord/devmarkt/services/UserService.java
Labels: enhancement

#119 Add option to rewrite errors to warnings
  dangerfile.js
Labels: tooling

#118 Enhance tempaltes
  backend/src/main/java/club/devcord/devmarkt/entities/auth/Role.java
  backend/src/main/java/club/devcord/devmarkt/entities/template/Question.java
  backend/src/main/java/club/devcord/devmarkt/entities/template/QuestionId.java
  backend/src/main/java/club/devcord/devmarkt/graphql/GraphQLFactory.java
  backend/src/main/java/club/devcord/devmarkt/graphql/TemplateNameScalar.java
  backend/src/main/java/club/devcord/devmarkt/graphql/role/RoleQuery.java
  backend/src/main/java/club/devcord/devmarkt/graphql/template/QuestionMutation.java
  backend/src/main/java/club/devcord/devmarkt/repositories/QuestionRepo.java
  backend/src/main/java/club/devcord/devmarkt/repositories/TemplateRepo.java
  backend/src/main/java/club/devcord/devmarkt/responses/question/QuestionSuccess.java
  backend/src/main/java/club/devcord/devmarkt/responses/role/RoleFailed.java
  backend/src/main/java/club/devcord/devmarkt/responses/role/RoleResponse.java
  backend/src/main/java/club/devcord/devmarkt/services/QuestionService.java
  backend/src/main/java/club/devcord/devmarkt/services/UserService.java
  backend/src/main/resources/db/migrations/V3__Enhance_Questions.sql
  backend/src/main/resources/db/seeder/R__Seed_Templates.sql
  backend/src/main/resources/graphql/schemas/common.graphql
  backend/src/main/resources/graphql/schemas/misc.graphql
  backend/src/main/resources/graphql/schemas/question.graphql
  backend/src/main/resources/graphql/schemas/role.graphql
  backend/src/main/resources/graphql/schemas/template.graphql
  backend/src/main/resources/graphql/schemas/user.graphql
  backend/src/test/java/club/devcord/devmarkt/DevmarktTest.java
  backend/src/test/java/club/devcord/devmarkt/Helpers.java
  backend/src/test/java/club/devcord/devmarkt/Seed.java
  backend/src/test/java/club/devcord/devmarkt/graphql/question/QuestionMutationTest.java
  backend/src/test/java/club/devcord/devmarkt/graphql/question/QuestionQueryTest.java
  backend/src/test/java/club/devcord/devmarkt/graphql/template/DataFetchingEnviromentStub.java
  backend/src/test/java/club/devcord/devmarkt/graphql/template/TemplateMutationTest.java
  backend/src/test/java/club/devcord/devmarkt/graphql/template/TemplateQueryTest.java
  backend/src/test/java/club/devcord/devmarkt/logging/LoggingUtilTest.java
  backend/src/test/java/club/devcord/devmarkt/repositories/QuestionRepoTest.java
  backend/src/test/java/club/devcord/devmarkt/repositories/TemplateRepoTest.java
  backend/src/test/java/club/devcord/devmarkt/services/QuestionServiceTest.java
  backend/src/test/java/club/devcord/devmarkt/services/TemplateServiceTest.java
  backend/src/test/resources/application-test.yml
  qa/src/fixtures/template/create.json
  qa/src/fixtures/template/only-questions.json
  qa/src/fixtures/template/templates.json
  qa/src/graphql/template/create-template.graphql
  qa/src/graphql/template/delete-template.graphql
  qa/src/graphql/template/templates-only-questions.graphql
  qa/src/graphql/template/templates.graphql
  qa/src/spec/template.spec.js
Labels: enhancement, danger-ignore-fail

#124 Remove obsolete linting rule
  dangerfile.js
Labels: tooling

#126 Remove testcontainers dependency
  backend/build.gradle.kts
Labels: dependencies
