Repository devcordde/devmarkt-backend, pull requests merged in 2023-07, with the labels that each got.

#208 update logback dependency
  backend/build.gradle.kts
Labels: bug

#210 Fix cached plan error
  backend/src/main/java/club/devcord/devmarkt/qa/QaDatabaseSeeding.java
Labels: qa

#213 update micronaut to 3.9.4
  gradle.properties
Labels: dependencies

#214 update gradle wrapper to 8.2.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies, tooling

#217 update action/codeql/autobuild to v2
  .github/workflows/codeql-analysis.yml
Labels: dependencies, tooling
